"""add warehoses&warehoses tables

Revision ID: a501b204d95a
Revises: 
Create Date: 2023-12-23 18:19:54.926005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a501b204d95a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houseslist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ware_house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ownerID', sa.Integer(), nullable=False),
    sa.Column('WareHouseID', sa.Integer(), nullable=False),
    sa.Column('date_rented', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['WareHouseID'], ['houseslist.id'], ),
    sa.ForeignKeyConstraint(['ownerID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ware_house')
    op.drop_table('houseslist')
    # ### end Alembic commands ###
