"""add comment table

Revision ID: aba9b2fceb3f
Revises: e04ac6635055
Create Date: 2023-12-12 19:34:36.549859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba9b2fceb3f'
down_revision = 'e04ac6635055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ownerID', sa.Integer(), nullable=False),
    sa.Column('postID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ownerID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['postID'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
